#!/usr/bin/env ruby -w
require 'time'
require 'rake'
require 'benchmark'

  FileList['spec/**/*_spec.rb'].sort.select do |fn|
    puts "rspec #{fn}"
    system "rspec #{fn}"
  end
  system('rspec')
end